// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductionTrackerApi.Context;

#nullable disable

namespace ProductionTrackerApi.Migrations
{
    [DbContext(typeof(ProductionTrackerContext))]
    partial class ProductionTrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductionTrackerApi.Models.ProductionOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("varchar(9)")
                        .HasDefaultValue("PENDING");

                    b.HasKey("Id")
                        .HasName("PK_ProductionOrder_ProductionOrderId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.ToTable("ProductionOrders");
                });

            modelBuilder.Entity("ProductionTrackerApi.Models.Step", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProductionOrderId")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_Step_StepId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("Steps", t =>
                        {
                            t.HasCheckConstraint("CK_End_After_Start", "[End] > [Start]");
                        });
                });

            modelBuilder.Entity("ProductionTrackerApi.Models.Step", b =>
                {
                    b.HasOne("ProductionTrackerApi.Models.ProductionOrder", "ProductionOrder")
                        .WithMany("Steps")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("ProductionTrackerApi.Models.ProductionOrder", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
